const PRODUCTS_LIMIT = 20

const PRODUCT_STARS = 5

const IMAGE_PLACEHOLDER = 'https://placehold.co/400'

const PRODUCTS_OFFSET = 100

export { PRODUCTS_LIMIT, PRODUCT_STARS, IMAGE_PLACEHOLDER, PRODUCTS_OFFSET }
